defaults:
  - _self_
  - slurm
  - override hydra/sweeper: SMAC

hydra:
  sweeper:
    smac_kwargs:
      intensifier: Not-HB
      max_budget: 5
      max_parallelization: .1
    budget_variable: num_steps

    saving_variable: saved_neural_nets
    budget: 10 # The amounts of jobs


    search_space:  # TODO adjust search space
      hyperparameters:
        x0:
          type: uniform_float
          lower: -5
          upper: 10
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 15
          log: false
          default_value: 2
    
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

x0: 3
x1: 4

seed: None
num_steps: 10
saved_neural_nets: blablabla