defaults:
  - _self_
  # - slurm
  - configspace: small_space_config
  - override hydra/sweeper: SMAC

hydra:
  sweeper:
    smac_kwargs:
      intensifier: Not-HB
      max_budget: 500000 # Internal Budget of one target function run
      
      # Parralelisation Parameters
      job_array_size_limit: 5
      max_parallelization: .001 
      # at most min(job_array_size_limit, max(1, int(max_parallelization * n_trials))) target functions are executed in parrallel

      deterministic: True # whether or nto the env is deterministic
      
      seeds: [0,1,2,3,4] # seeds passed to each worker - so we alsways have the same seeds
      # TODO Assuming wokring with seeds makes sense, how do we go from here
      # to plots that contain uncertainty? I assume that i need to log that myself, because
      # there is no inbuilt function to do so

    budget: 20 # The budget for SMAC

    budget_variable: non_hyperparameters.total_timesteps
    saving_variable: non_hyperparameters.saved_neural_nets

    search_space: ${configspace}

    
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Beloww are hyperparameters
batch_size: 64
clip_range: 0.2
clip_range_vf: Null  # If separate clipping is used for value function, otherwise can be the same as `clip_range`
ent_coef: 0.01
gae_lambda: 0.95
learning_rate: 0.00025
max_grad_norm: 0.5
n_epochs: 10
n_steps: 2048
normalize_advantage: False
vf_coef: 0.5

# Below are not hpo parameters. Seed is currenlty not allowed to be outside of section
seed: 0 
non_hyperparameters:
  trial_number: 0
  experiment_id: Null
  environment_id: MiniHack-Room-Random-5x5-v0
  env_seed: 0
  saved_neural_nets: blablabla
  observation_keys: [glyphs, chars, colors, specials, blstats]
  max_episode_steps: 25 # TODO should this be a relevant hp?
  parallel_vec_envs: 5
  n_evaluation_episodes: 10
  n_evaluation_rounds: 20
  total_timesteps: Null # Defined at top with budget

PY_EXPERIMENTER: 
  n_jobs: 1

  Database:
    provider: mysql
    database: fehring_growing_nn_test
    table:
      name: black_box_development
      keyfields: 
        environment_id:
          type: VARCHAR(50)
        env_seed:
          type: INT
        saved_neural_nets:
          type: VARCHAR(50)
        observation_keys:
          type: VARCHAR(200)
        max_episode_steps:
          type: INT
        parallel_vec_envs:
          type: INT
        seed:
          type: INT
        n_evaluation_episodes:
          type: INT
        n_evaluation_rounds:
          type: int
        total_timesteps: 
          type: int
    logtables:
      configurations:
        environment_id: VARCHAR(50)
        trial_number: INT
        worker_number: INT # The number of the worker used by hypersweeper to evaluate the current configuration
        worker_seed: INT # The seed provided to the worker to evalaute the curernt configuration
        batch_size: INT
        clip_range: FLOAT
        clip_range_vf: FLOAT
        ent_coef: FLOAT
        gae_lambda: FLOAT
        learning_rate: FLOAT
        max_grad_norm: FLOAT
        n_epochs: INT
        n_steps: INT
        normalize_advantage: BOOLEAN
        vf_coef: FLOAT
        final_score: FLOAT
        final_std: FLOAT
      training_process:
        worker_id: INT
        trial_number: INT
        timestep: INT
        evaluated_cost: FLOAT
        evaluated_stdev: FLOAT

      smac_callbacks:
        trial_number: INT
        cost: FLOAT

      final_evaluation_callback:
        trial_number: INT
        worker_number: INT
        final_score: FLOAT
        final_std: FLOAT
        episode_lengths: TEXT
        average_episode_lengths: FLOAT
        successfull: FLOAT
        rewards_per_episode: LONGTEXT