hyperparameters:
  ent_coef:
    type: uniform_float
    lower: 0.0
    upper: 0.3
  learning_rate:
    log: true
    type: uniform_float
    lower: 1.0e-04
    upper: 0.01
  n_epochs:
    lower: 5
    type: uniform_int
    upper: 20
  batch_size:
    choices:
    - 32
    - 64
    - 128
    - 256
    type: categorical
  momentum_reset:
    type: categorical
    choices:
    - True
    - False
  noise_std:
    type: uniform_float
    lower: 0.01
    upper: 1.0