hyperparameters:
  ent_coef:
    type: uniform_float
    lower: 0.0
    upper: 0.3
  learning_rate:
    log: true
    type: uniform_float
    lower: 1.0e-04
    upper: 0.01
  n_epochs:
    lower: 5
    type: uniform_integer
    upper: 20
